FROM rust:1-slim-bookworm AS builder
WORKDIR /usr/src/myapp
COPY . .
RUN apt-get update && apt-get install -y nasm
RUN cargo install --profile release --path .

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libc6 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/imgc /usr/local/bin/imgc
CMD ["imgc"]
